// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: etf/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetFundRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetFundRequest) Reset()         { *m = QueryGetFundRequest{} }
func (m *QueryGetFundRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetFundRequest) ProtoMessage()    {}
func (*QueryGetFundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b29f902a0b14e0e, []int{0}
}
func (m *QueryGetFundRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetFundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetFundRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetFundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetFundRequest.Merge(m, src)
}
func (m *QueryGetFundRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetFundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetFundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetFundRequest proto.InternalMessageInfo

func (m *QueryGetFundRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetFundResponse struct {
	Fund Fund `protobuf:"bytes,1,opt,name=fund,proto3" json:"fund"`
}

func (m *QueryGetFundResponse) Reset()         { *m = QueryGetFundResponse{} }
func (m *QueryGetFundResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetFundResponse) ProtoMessage()    {}
func (*QueryGetFundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b29f902a0b14e0e, []int{1}
}
func (m *QueryGetFundResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetFundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetFundResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetFundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetFundResponse.Merge(m, src)
}
func (m *QueryGetFundResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetFundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetFundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetFundResponse proto.InternalMessageInfo

func (m *QueryGetFundResponse) GetFund() Fund {
	if m != nil {
		return m.Fund
	}
	return Fund{}
}

type QueryAllFundRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllFundRequest) Reset()         { *m = QueryAllFundRequest{} }
func (m *QueryAllFundRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllFundRequest) ProtoMessage()    {}
func (*QueryAllFundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b29f902a0b14e0e, []int{2}
}
func (m *QueryAllFundRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllFundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllFundRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllFundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllFundRequest.Merge(m, src)
}
func (m *QueryAllFundRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllFundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllFundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllFundRequest proto.InternalMessageInfo

func (m *QueryAllFundRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllFundResponse struct {
	Fund       []Fund              `protobuf:"bytes,1,rep,name=fund,proto3" json:"fund"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllFundResponse) Reset()         { *m = QueryAllFundResponse{} }
func (m *QueryAllFundResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllFundResponse) ProtoMessage()    {}
func (*QueryAllFundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b29f902a0b14e0e, []int{3}
}
func (m *QueryAllFundResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllFundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllFundResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllFundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllFundResponse.Merge(m, src)
}
func (m *QueryAllFundResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllFundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllFundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllFundResponse proto.InternalMessageInfo

func (m *QueryAllFundResponse) GetFund() []Fund {
	if m != nil {
		return m.Fund
	}
	return nil
}

func (m *QueryAllFundResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryFundPriceRequest struct {
	Ticker string `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
}

func (m *QueryFundPriceRequest) Reset()         { *m = QueryFundPriceRequest{} }
func (m *QueryFundPriceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFundPriceRequest) ProtoMessage()    {}
func (*QueryFundPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b29f902a0b14e0e, []int{4}
}
func (m *QueryFundPriceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFundPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFundPriceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFundPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFundPriceRequest.Merge(m, src)
}
func (m *QueryFundPriceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFundPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFundPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFundPriceRequest proto.InternalMessageInfo

func (m *QueryFundPriceRequest) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

type QueryFundPriceResponse struct {
}

func (m *QueryFundPriceResponse) Reset()         { *m = QueryFundPriceResponse{} }
func (m *QueryFundPriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFundPriceResponse) ProtoMessage()    {}
func (*QueryFundPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b29f902a0b14e0e, []int{5}
}
func (m *QueryFundPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFundPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFundPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFundPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFundPriceResponse.Merge(m, src)
}
func (m *QueryFundPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFundPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFundPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFundPriceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryGetFundRequest)(nil), "defundhub.defund.etf.QueryGetFundRequest")
	proto.RegisterType((*QueryGetFundResponse)(nil), "defundhub.defund.etf.QueryGetFundResponse")
	proto.RegisterType((*QueryAllFundRequest)(nil), "defundhub.defund.etf.QueryAllFundRequest")
	proto.RegisterType((*QueryAllFundResponse)(nil), "defundhub.defund.etf.QueryAllFundResponse")
	proto.RegisterType((*QueryFundPriceRequest)(nil), "defundhub.defund.etf.QueryFundPriceRequest")
	proto.RegisterType((*QueryFundPriceResponse)(nil), "defundhub.defund.etf.QueryFundPriceResponse")
}

func init() { proto.RegisterFile("etf/query.proto", fileDescriptor_9b29f902a0b14e0e) }

var fileDescriptor_9b29f902a0b14e0e = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0x4f, 0xd4, 0x40,
	0x18, 0xc6, 0x3b, 0xb0, 0x60, 0x18, 0x13, 0x4d, 0xc6, 0x4a, 0x48, 0x43, 0xaa, 0x56, 0x82, 0x2e,
	0xe0, 0x4c, 0x40, 0xbf, 0x00, 0x98, 0xc0, 0xc5, 0x03, 0xf6, 0x68, 0xe2, 0x61, 0xda, 0xce, 0xd6,
	0xc6, 0x32, 0x53, 0x3a, 0x53, 0x03, 0x31, 0x5e, 0x3c, 0x78, 0xf1, 0xa2, 0x31, 0x7e, 0x11, 0x3f,
	0x05, 0x47, 0x12, 0x2f, 0x9e, 0x8c, 0xd9, 0xf5, 0x83, 0x98, 0xf9, 0x03, 0xd2, 0xb5, 0xa9, 0x7b,
	0x7b, 0x67, 0xfb, 0xbc, 0xcf, 0xf3, 0x7b, 0xe7, 0x9d, 0x85, 0x37, 0x99, 0x1a, 0x91, 0xe3, 0x86,
	0xd5, 0xa7, 0xb8, 0xaa, 0x85, 0x12, 0xc8, 0xcf, 0xd8, 0xa8, 0xe1, 0xd9, 0xab, 0x26, 0xc1, 0xb6,
	0xc2, 0x4c, 0x8d, 0x82, 0xd5, 0x5c, 0x88, 0xbc, 0x64, 0x84, 0x56, 0x05, 0xa1, 0x9c, 0x0b, 0x45,
	0x55, 0x21, 0xb8, 0xb4, 0x3d, 0xc1, 0x46, 0x2a, 0xe4, 0x91, 0x90, 0x24, 0xa1, 0x92, 0x59, 0x33,
	0xf2, 0x66, 0x3b, 0x61, 0x8a, 0x6e, 0x93, 0x8a, 0xe6, 0x05, 0x37, 0x62, 0xa7, 0xbd, 0xa1, 0x03,
	0x8d, 0xaf, 0x3d, 0xfb, 0xb9, 0xc8, 0x85, 0x29, 0x89, 0xae, 0xec, 0xaf, 0xd1, 0x26, 0xbc, 0xf5,
	0x5c, 0xfb, 0x1c, 0x30, 0xb5, 0xdf, 0xf0, 0x2c, 0x66, 0xc7, 0x0d, 0x93, 0x0a, 0xf9, 0x70, 0xa1,
	0xe0, 0x19, 0x3b, 0x59, 0x01, 0x77, 0xc1, 0xc3, 0xa5, 0xd8, 0x1e, 0xa2, 0x67, 0xd0, 0x6f, 0x8b,
	0x65, 0x25, 0xb8, 0x64, 0xe8, 0x09, 0x1c, 0xe8, 0x20, 0x23, 0xbe, 0xbe, 0x13, 0xe0, 0xae, 0xc9,
	0xb0, 0xee, 0xd8, 0x1b, 0x9c, 0xfd, 0xbc, 0xe3, 0xc5, 0x46, 0x1d, 0xbd, 0x74, 0xd1, 0xbb, 0x65,
	0x79, 0x35, 0x7a, 0x1f, 0xc2, 0xbf, 0xb3, 0x38, 0xcb, 0x75, 0x6c, 0x07, 0xc7, 0x7a, 0x70, 0x6c,
	0x6f, 0xd1, 0x0d, 0x8e, 0x0f, 0x69, 0xce, 0x5c, 0x6f, 0x7c, 0xa5, 0x33, 0xfa, 0x0a, 0x1c, 0xed,
	0xa5, 0xff, 0x3f, 0xb4, 0xf3, 0xb3, 0xd3, 0xa2, 0x83, 0x16, 0xd6, 0x9c, 0xc1, 0x7a, 0xf0, 0x5f,
	0x2c, 0x1b, 0xd9, 0xe2, 0x22, 0xf0, 0xb6, 0xc1, 0xd2, 0x09, 0x87, 0x75, 0x91, 0x5e, 0xc0, 0xa3,
	0x65, 0xb8, 0xa8, 0x8a, 0xf4, 0x35, 0xab, 0xdd, 0xa5, 0xbb, 0x53, 0xb4, 0x02, 0x97, 0xa7, 0x1b,
	0xac, 0xed, 0xce, 0xb7, 0x79, 0xb8, 0x60, 0x3e, 0xa1, 0x8f, 0x00, 0x0e, 0xf4, 0x77, 0x34, 0xec,
	0x1e, 0xa7, 0x63, 0xc7, 0xc1, 0xc6, 0x2c, 0x52, 0x9b, 0x14, 0x6d, 0xbd, 0xff, 0xfe, 0xfb, 0xcb,
	0xdc, 0x3a, 0x5a, 0x23, 0x56, 0xf9, 0xa8, 0xa4, 0x89, 0x74, 0x35, 0xb9, 0x78, 0x68, 0xe4, 0xad,
	0x79, 0x26, 0xef, 0xd0, 0x07, 0x00, 0xaf, 0xe9, 0xf6, 0xdd, 0xb2, 0xec, 0x05, 0x6a, 0x6f, 0xbe,
	0x17, 0x68, 0x6a, 0x89, 0xd1, 0x9a, 0x01, 0x0a, 0xd1, 0x6a, 0x1f, 0x10, 0xfa, 0x0c, 0xe0, 0xd2,
	0xe5, 0xb5, 0xa1, 0xcd, 0x1e, 0xff, 0xe9, 0x6d, 0x04, 0x5b, 0xb3, 0x89, 0x1d, 0xce, 0xd0, 0xe0,
	0xdc, 0x47, 0xf7, 0xfa, 0x70, 0x4c, 0xcb, 0xde, 0xd3, 0xb3, 0x71, 0x08, 0xce, 0xc7, 0x21, 0xf8,
	0x35, 0x0e, 0xc1, 0xa7, 0x49, 0xe8, 0x9d, 0x4f, 0x42, 0xef, 0xc7, 0x24, 0xf4, 0x5e, 0x0c, 0xf3,
	0x42, 0xe9, 0xb8, 0x54, 0x1c, 0x75, 0xd9, 0x9c, 0x18, 0x23, 0x75, 0x5a, 0x31, 0x99, 0x2c, 0x9a,
	0x7f, 0xef, 0xe3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x61, 0xfb, 0xdb, 0x56, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a fund by index.
	Fund(ctx context.Context, in *QueryGetFundRequest, opts ...grpc.CallOption) (*QueryGetFundResponse, error)
	// Queries a list of fund items.
	FundAll(ctx context.Context, in *QueryAllFundRequest, opts ...grpc.CallOption) (*QueryAllFundResponse, error)
	// Queries a list of fundPrice items.
	FundPrice(ctx context.Context, in *QueryFundPriceRequest, opts ...grpc.CallOption) (*QueryFundPriceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Fund(ctx context.Context, in *QueryGetFundRequest, opts ...grpc.CallOption) (*QueryGetFundResponse, error) {
	out := new(QueryGetFundResponse)
	err := c.cc.Invoke(ctx, "/defundhub.defund.etf.Query/Fund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FundAll(ctx context.Context, in *QueryAllFundRequest, opts ...grpc.CallOption) (*QueryAllFundResponse, error) {
	out := new(QueryAllFundResponse)
	err := c.cc.Invoke(ctx, "/defundhub.defund.etf.Query/FundAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FundPrice(ctx context.Context, in *QueryFundPriceRequest, opts ...grpc.CallOption) (*QueryFundPriceResponse, error) {
	out := new(QueryFundPriceResponse)
	err := c.cc.Invoke(ctx, "/defundhub.defund.etf.Query/FundPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a fund by index.
	Fund(context.Context, *QueryGetFundRequest) (*QueryGetFundResponse, error)
	// Queries a list of fund items.
	FundAll(context.Context, *QueryAllFundRequest) (*QueryAllFundResponse, error)
	// Queries a list of fundPrice items.
	FundPrice(context.Context, *QueryFundPriceRequest) (*QueryFundPriceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Fund(ctx context.Context, req *QueryGetFundRequest) (*QueryGetFundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fund not implemented")
}
func (*UnimplementedQueryServer) FundAll(ctx context.Context, req *QueryAllFundRequest) (*QueryAllFundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FundAll not implemented")
}
func (*UnimplementedQueryServer) FundPrice(ctx context.Context, req *QueryFundPriceRequest) (*QueryFundPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FundPrice not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Fund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Fund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/defundhub.defund.etf.Query/Fund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Fund(ctx, req.(*QueryGetFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FundAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FundAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/defundhub.defund.etf.Query/FundAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FundAll(ctx, req.(*QueryAllFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FundPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFundPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FundPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/defundhub.defund.etf.Query/FundPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FundPrice(ctx, req.(*QueryFundPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "defundhub.defund.etf.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fund",
			Handler:    _Query_Fund_Handler,
		},
		{
			MethodName: "FundAll",
			Handler:    _Query_FundAll_Handler,
		},
		{
			MethodName: "FundPrice",
			Handler:    _Query_FundPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "etf/query.proto",
}

func (m *QueryGetFundRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetFundRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetFundRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetFundResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetFundResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetFundResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Fund.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllFundRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllFundRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllFundRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllFundResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllFundResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllFundResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Fund) > 0 {
		for iNdEx := len(m.Fund) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Fund[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryFundPriceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFundPriceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFundPriceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ticker) > 0 {
		i -= len(m.Ticker)
		copy(dAtA[i:], m.Ticker)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Ticker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFundPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFundPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFundPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetFundRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetFundResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Fund.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllFundRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllFundResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Fund) > 0 {
		for _, e := range m.Fund {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFundPriceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Ticker)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFundPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetFundRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetFundRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetFundRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetFundResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetFundResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetFundResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fund", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fund.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllFundRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllFundRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllFundRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllFundResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllFundResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllFundResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fund", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fund = append(m.Fund, Fund{})
			if err := m.Fund[len(m.Fund)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFundPriceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFundPriceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFundPriceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ticker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ticker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFundPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFundPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFundPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
